#!/bin/sh
(
echo '
<deck>
<slide>
<text xp="10"  yp="85" sp="7">dchart</text>
<text xp="35"  yp="85" sp="6" color="maroon">charts for deck</text>'
dchart -fulldeck=f -textsize=1		-left=10 -right=65 -top=70 -bottom=40 -color=steelblue -bar=f -vol=f -chartitle="BITCOIN to USD" -vol -val=f -xlabel=100 -xlast -line -yaxis -grid -csv -csvcol=Date,Close -yrange=0,20000,4000 BTC-USD.csv 
dchart -fulldeck=f -textsize=1  	-left=10 -right=65 -top=30 -bottom=15 -color=orange    -val=f -yaxis -xlabel=0  -grid -bar -csv -csvcol=Date,Volume BTC-USD.csv
dchart -fulldeck=f -textsize=0.75	-left=75 -right=95 -top=75 -bottom=55 -xlabel=3 -xlast AAPLvol.d
dchart -fulldeck=f -textsize=0.75	-left=75 -right=95 -top=45 -bottom=25 -wbar browser.d
dchart -fulldeck=f -textsize=0.75	-left 75 -top 25   -ls=1.5 -val=f     -pgrid incar.d
echo '
</slide>
</deck>'
) 